name: Deploy to Pages

on:
  workflow_dispatch:

permissions:
  deployments: write
  contents: write  # Added this to allow pushing to branches
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed to get all history for the branch

      - name: Install, build, and upload your site
        uses: withastro/action@v2
        env: 
            PUBLIC_TINA_CLIENT_ID: ${{ secrets.PUBLIC_TINA_CLIENT_ID }}
            TINA_TOKEN: ${{ secrets.TINA_TOKEN }}
            SITE_URL: ${{ secrets.SITE_URL }}
      - name: Publish
        uses: cloudflare/pages-action@v1
        with:
              apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
              accountId: 507190fcd28b888632b1f95628832c6a 
              projectName: tina-astro-kemo2 # e.g. 'my-project'
              directory: dist # e.g. 'dist'
              gitHubToken: ${{ secrets.GITHUB_TOKEN }}
