name: Deploy to Pages

on:
  workflow_dispatch:

permissions:
  deployments: write
  contents: write  # Added this to allow pushing to branches
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed to get all history for the branch

      - name: Install, build, and upload your site
        uses: withastro/action@v2
        env: 
            PUBLIC_TINA_CLIENT_ID: ${{ secrets.PUBLIC_TINA_CLIENT_ID }}
            TINA_TOKEN: ${{ secrets.TINA_TOKEN }}
            SITE_URL: ${{ secrets.SITE_URL }}
      # Run a build step here if your project requires
      - name: Deploy to Cloudflare Pages
        uses: andykenward/github-actions-cloudflare-pages@v2.3.2
        id: pages
        with:
          cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          cloudflare-account-id: 507190fcd28b888632b1f95628832c6a 
          cloudflare-project-name: tina-astro-kemo
          directory: dist
          github-token: ${{ secrets.GITHUB_TOKEN }}

  